name: Build
on: workflow_dispatch
defaults:
  run:
    shell: bash

jobs:
  build_linux:
    name: Build (Linux x86/x86_64)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - linux64
          - linux32
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install lua5.1 libc6-dev-i386
      - name: Build artifact
        run: make ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-x86-x86_64
          path: build/linux_*/liblua_pluginscript.so
  build_windows:
    name: Build (Windows x86/x86_64)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - mingw-windows32 CC=gcc
          - mingw-windows64 CC=gcc
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install lua5.1 gcc-mingw-w64
      - name: Build artifact
        run: make ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-x86-x86_64
          path: build/windows_*/lua*.dll
  build_osx_ios:
    name: Build (OSX arm64/x86_64, iOS arm64, iOS simulator arm64/x86_64)
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - osx64
          - ios64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: brew install lua@5.1
      - name: Build artifact
        run: make ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: osx-ios-arm64-x86_64
          path: |
            build/osx_arm64_x86_64/lua_pluginscript.dylib
            build/ios_arm64/lua_pluginscript.dylib
            build/ios_simulator_arm64_x86_64/lua_pluginscript.dylib

