name: Build
on: push
defaults:
  run:
    shell: bash

jobs:
  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - linux64
          - linux32
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install lua5.1 libc6-dev-i386
      - name: Build artifact
        run: make ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: linux-x86-x86_64
          path: |
            build/linux_x86/liblua_pluginscript.so
            build/linux_x86_64/liblua_pluginscript.so

  build_windows:
    name: Build Windows
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - mingw-windows32
          - mingw-windows64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install lua5.1 libc6-dev-i386 gcc-mingw-w64
      - name: Build artifact
        run: make ${{ matrix.target }}
        env:
          CC: gcc
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-x86-x86_64
          path: |
            build/windows_x86/lua51.dll
            build/windows_x86/lua_pluginscript.dll
            build/windows_x86_64/lua51.dll
            build/windows_x86_64/lua_pluginscript.dll

  build_osx_ios:
    name: Build OSX/iOS
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - osx64
          - ios64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: brew install lua@5.1
      - name: Build artifact
        run: make ${{ matrix.target }}
        env:
          LUA_BIN: lua5.1
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: osx-ios-arm64-x86_64
          path: |
            build/osx_arm64_x86_64/lua_pluginscript.dylib
            build/ios_arm64/lua_pluginscript.dylib
            build/ios_simulator_arm64_x86_64/lua_pluginscript.dylib

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - android-armv7a
          - android-aarch64
          - android-x86
          - android-x86_64
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install lua5.1 libc6-dev-i386
      - name: Build artifact
        run: make ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-armv7a-aarch64-x86-x86_64
          path: build/android_*/liblua_pluginscript.so

