name: Build
on: push
defaults:
  run:
    shell: bash

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install lua5.1 libc6-dev-i386
      - name: Install Godot
        uses: vitorgus/setup-godot@v1
        with:
          godot-version: 3.4
          download-templates: false
      - name: Build and test
        run: make test-linux64 DEBUG=1

